-- QUESTION 1
UPDATE TBL_DEPTS
SET SCORES = (
  SELECT MAX(SCORES) FROM TBL_DEPTS T1 WHERE T1.DEPT = TBL_DEPTS.DEPT
);


-- QUESTION 2
SELECT SPLIT_PART(BOOK_CODE, '-', 2) AS BOOK_TITLE
FROM TBL_BOOKS;
